# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HotelRelief' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HotelRelief
  pod 'Firebase/Core'

  target 'HotelReliefTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HotelRelief-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HotelRelief-tvOS

  target 'HotelRelief-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
