# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
project './HotelRelief.xcworkspace'
target 'HotelRelief' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HotelRelief
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => ‘./../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTAdSupport',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
    # Add any other subspecs you want to use in your project
  ]

  target 'HotelReliefTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HotelRelief-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HotelRelief-tvOS

  target 'HotelRelief-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
#post_install do |installer|
  #installer.pods_project.targets.each do |target|
    #if target.name == "React"
   #   target.remove_from_project
  #  end
 # end
#end
